# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='poke',
            name='poked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedby', to='new_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokeduser', to='new_app.User'),
        ),
    ]
